{"uid":"a2112165a156aedd","name":"Check App build and running & Check app elements exist","fullName":"Check App build and running & Check app elements exist","historyId":"c1e712afb221157f3d586affd994cf6a","time":{"start":1698734834019,"stop":1698734835061,"duration":1042},"status":"broken","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at webpack/container/reference/app_05 (http://localhost:3001/main.js:93:25)\n    at __webpack_require__ (http://localhost:3001/main.js:130:41)\n    at initExternal (http://localhost:3001/main.js:407:28)\n    at __webpack_require__.I (http://localhost:3001/main.js:425:15)\n    at <unknown> (http://localhost:3001/main.js:536:47)\n    at webpack/sharing/consume/default/react/react?2849 (http://localhost:3001/main.js:590:72)\n    at <unknown> (http://localhost:3001/main.js:651:56)\n    at Array.forEach (<anonymous>)\n    at __webpack_require__.f.consumes (http://localhost:3001/main.js:634:36)\n    at <unknown> (http://localhost:3001/main.js:204:40)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at webpack/container/reference/app_05 (http://localhost:3001/main.js:93:25)\n    at __webpack_require__ (http://localhost:3001/main.js:130:41)\n    at initExternal (http://localhost:3001/main.js:407:28)\n    at __webpack_require__.I (http://localhost:3001/main.js:425:15)\n    at <unknown> (http://localhost:3001/main.js:536:47)\n    at webpack/sharing/consume/default/react/react?2849 (http://localhost:3001/main.js:590:72)\n    at <unknown> (http://localhost:3001/main.js:651:56)\n    at Array.forEach (<anonymous>)\n    at __webpack_require__.f.consumes (http://localhost:3001/main.js:634:36)\n    at <unknown> (http://localhost:3001/main.js:204:40)","steps":[{"name":"\"before each\" hook","time":{"start":1698734834020,"stop":1698734835061,"duration":1041},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at webpack/container/reference/app_05 (http://localhost:3001/main.js:93:25)\n    at __webpack_require__ (http://localhost:3001/main.js:130:41)\n    at initExternal (http://localhost:3001/main.js:407:28)\n    at __webpack_require__.I (http://localhost:3001/main.js:425:15)\n    at <unknown> (http://localhost:3001/main.js:536:47)\n    at webpack/sharing/consume/default/react/react?2849 (http://localhost:3001/main.js:590:72)\n    at <unknown> (http://localhost:3001/main.js:651:56)\n    at Array.forEach (<anonymous>)\n    at __webpack_require__.f.consumes (http://localhost:3001/main.js:634:36)\n    at <unknown> (http://localhost:3001/main.js:204:40)","steps":[{"name":"visit http://localhost:3001","time":{"start":1698734834239,"stop":1698734835061,"duration":822},"status":"failed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"uncaught exception ScriptExternalLoadError: Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05","time":{"start":1698734835060,"stop":1698734835060,"duration":0},"status":"failed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":0,"hasContent":true}],"attachments":[{"uid":"4454ebb3226eaa34","name":"e2e/runAllComprehensiveDemoReact16Tests.cy.ts:2023-10-31T06:47:14.662Z:attempt-1","source":"4454ebb3226eaa34.png","type":"image/png","size":164614},{"uid":"169cbdd6f9b6e641","name":"video recording","source":"169cbdd6f9b6e641.mp4","type":"video/mp4","size":2799774}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":2,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"e2e.runAllComprehensiveDemoReact16Tests.cy.ts"},{"name":"parentSuite","value":"Comprehemsive Demo React 16"},{"name":"suite","value":"Check is Comprehensive Demo App1 working and have elements"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"a2112165a156aedd.json","parameterValues":[]}