{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3005/remoteEntry.js)\nwhile loading \"./components\" from webpack/container/reference/app_05\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check App build and running & Check app elements exist","uid":"aef0269cfe2bcd6c","parentUid":"24fa4ab030acaf5ed335e04599595b90","status":"broken","time":{"start":1698618070829,"stop":1698618071649,"duration":820},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":4,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"24fa4ab030acaf5ed335e04599595b90"},{"name":"`cy.visit()` failed trying to load:\n\nhttp://localhost:3002//shop\n\nThe response we received from your web server was:\n\n  > 500: Internal Server Error\n\nThis was considered a failure because the status code was not `2xx`.\n\nThis http request was redirected '1' time to:\n\n  - 308: http://localhost:3002/shop\n\nIf you do not want status codes to cause failures pass the option: `failOnStatusCode: false`","children":[{"name":"Check the header content of Shop page","uid":"fa10a1d0b3ef34ab","parentUid":"fc7d2bf7fe16529721b0bcd46f598781","status":"broken","time":{"start":1698619222770,"stop":1698619223348,"duration":578},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"fc7d2bf7fe16529721b0bcd46f598781"}],"uid":"bdbf199525818fae7a8651db9eafe741"},{"name":"Product defects","children":[{"name":"Timed out retrying after 10000ms: Expected to find element: `h1`, but never found it.","children":[{"name":"Check App1 and App2 elements","uid":"9e30de833eba5095","parentUid":"23fd062f6b4cc0af7a7ed54a88a82e22","status":"failed","time":{"start":1698618072418,"stop":1698618082863,"duration":10445},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"23fd062f6b4cc0af7a7ed54a88a82e22"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Additional keys were returned from `getServerSideProps`. Properties intended for your component must be nested under the `props` key, e.g.:\n\n\treturn { props: { title: 'My Title', content: '...' } }\n\nKeys that need to be moved: userId, id, title, completed.\nRead more: https://nextjs.org/docs/messages/invalid-getserversideprops-value\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check that Shop navigation link works","uid":"69c7a430be368282","parentUid":"9923ecdd3da820d4b0811512ad94f2f1","status":"failed","time":{"start":1698619213206,"stop":1698619217582,"duration":4376},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":true,"parameters":[],"tags":[]},{"name":"Check that Shop text navigation link works","uid":"37c321597ffd909a","parentUid":"9923ecdd3da820d4b0811512ad94f2f1","status":"failed","time":{"start":1698619245822,"stop":1698619249738,"duration":3916},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":3,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"9923ecdd3da820d4b0811512ad94f2f1"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}