{"uid":"5e8164e753372803","name":"Checks all texted links visibility","fullName":"Checks all texted links visibility","historyId":"46a39aff9bc844c0121b6d2029848cfb","time":{"start":1682970714211,"stop":1682970714211,"duration":0},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at eval (webpack://react-nested-routers_shell/./src/routing/Router.tsx?:13:90)\n    at ./src/routing/Router.tsx (http://localhost:8080/src_bootstrap_tsx.js:48:1)\n    at __webpack_require__ (http://localhost:8080/main.js:377:33)\n    at fn (http://localhost:8080/main.js:717:21)\n    at eval (webpack://react-nested-routers_shell/./src/App.tsx?:8:73)\n    at ./src/App.tsx (http://localhost:8080/src_bootstrap_tsx.js:18:1)\n    at __webpack_require__ (http://localhost:8080/main.js:377:33)\n    at fn (http://localhost:8080/main.js:717:21)\n    at eval (webpack://react-nested-routers_shell/./src/bootstrap.tsx?:5:62)\n    at ./src/bootstrap.tsx (http://localhost:8080/src_bootstrap_tsx.js:28:1)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at eval (webpack://react-nested-routers_shell/./src/routing/Router.tsx?:13:90)\n    at ./src/routing/Router.tsx (http://localhost:8080/src_bootstrap_tsx.js:48:1)\n    at __webpack_require__ (http://localhost:8080/main.js:377:33)\n    at fn (http://localhost:8080/main.js:717:21)\n    at eval (webpack://react-nested-routers_shell/./src/App.tsx?:8:73)\n    at ./src/App.tsx (http://localhost:8080/src_bootstrap_tsx.js:18:1)\n    at __webpack_require__ (http://localhost:8080/main.js:377:33)\n    at fn (http://localhost:8080/main.js:717:21)\n    at eval (webpack://react-nested-routers_shell/./src/bootstrap.tsx?:5:62)\n    at ./src/bootstrap.tsx (http://localhost:8080/src_bootstrap_tsx.js:28:1)","steps":[],"attachments":[{"uid":"e199c82ef016f1b8","name":"e2e/runAll.cy.ts:2023-05-01T19:51:42.696Z","source":"e199c82ef016f1b8.png","type":"image/png","size":142357},{"uid":"58b8623c6faadd5","name":"video recording","source":"58b8623c6faadd5.mp4","type":"video/mp4","size":3044086}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"e2e.runAll.cy.ts"},{"name":"parentSuite","value":"React Nested Routers"},{"name":"suite","value":"It checks shell app"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"8605b028f0ce85fc","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682970707275,"stop":1682970707275,"duration":0}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":5,"broken":0,"skipped":0,"passed":15,"unknown":0,"total":20},"items":[{"uid":"8144e3af98a614f6","reportUrl":"https://module-federation.github.io/module-federation-examples/941//#testresult/8144e3af98a614f6","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682966993021,"stop":1682966993021,"duration":0}},{"uid":"4aaf7e602dfa9941","reportUrl":"https://module-federation.github.io/module-federation-examples/940//#testresult/4aaf7e602dfa9941","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682964268633,"stop":1682964268633,"duration":0}},{"uid":"5b9ee9325127b9cd","reportUrl":"https://module-federation.github.io/module-federation-examples/937//#testresult/5b9ee9325127b9cd","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682786455123,"stop":1682786455123,"duration":0}},{"uid":"1e93667c23411e5a","reportUrl":"https://module-federation.github.io/module-federation-examples/934//#testresult/1e93667c23411e5a","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682786455123,"stop":1682786455123,"duration":0}},{"uid":"41c96e2d6a9fb3db","reportUrl":"https://module-federation.github.io/module-federation-examples/873//#testresult/41c96e2d6a9fb3db","status":"passed","time":{"start":1682318654095,"stop":1682318654095,"duration":0}},{"uid":"4f6b3aba549fc1fd","reportUrl":"https://module-federation.github.io/module-federation-examples/857//#testresult/4f6b3aba549fc1fd","status":"passed","time":{"start":1682292527984,"stop":1682292527984,"duration":0}},{"uid":"9c78b4bd339e1748","reportUrl":"https://module-federation.github.io/module-federation-examples/847//#testresult/9c78b4bd339e1748","status":"passed","time":{"start":1682242554193,"stop":1682242554193,"duration":0}},{"uid":"123b3566a2b32a0f","reportUrl":"https://module-federation.github.io/module-federation-examples/842//#testresult/123b3566a2b32a0f","status":"passed","time":{"start":1682242554193,"stop":1682242554193,"duration":0}},{"uid":"2fd8e98cb04d2911","reportUrl":"https://module-federation.github.io/module-federation-examples/840//#testresult/2fd8e98cb04d2911","status":"passed","time":{"start":1682242554193,"stop":1682242554193,"duration":0}},{"uid":"4d338cfba3038342","reportUrl":"https://module-federation.github.io/module-federation-examples/837//#testresult/4d338cfba3038342","status":"passed","time":{"start":1682217345494,"stop":1682217345494,"duration":0}},{"uid":"7147ac36f7a89885","reportUrl":"https://module-federation.github.io/module-federation-examples/833//#testresult/7147ac36f7a89885","status":"passed","time":{"start":1682211463745,"stop":1682211463745,"duration":0}},{"uid":"bc4a239eed5f2ea1","reportUrl":"https://module-federation.github.io/module-federation-examples/823//#testresult/bc4a239eed5f2ea1","status":"passed","time":{"start":1682201545703,"stop":1682201545703,"duration":0}},{"uid":"fe27fcae84a6d343","reportUrl":"https://module-federation.github.io/module-federation-examples/820//#testresult/fe27fcae84a6d343","status":"passed","time":{"start":1682198362859,"stop":1682198362859,"duration":0}},{"uid":"7a371e82ba90124","reportUrl":"https://module-federation.github.io/module-federation-examples/819//#testresult/7a371e82ba90124","status":"passed","time":{"start":1682200067091,"stop":1682200067091,"duration":0}},{"uid":"5ba173292bdc0b9","reportUrl":"https://module-federation.github.io/module-federation-examples/806//#testresult/5ba173292bdc0b9","status":"passed","time":{"start":1682130301826,"stop":1682130301827,"duration":1}},{"uid":"37c666fbece4c23e","reportUrl":"https://module-federation.github.io/module-federation-examples/804//#testresult/37c666fbece4c23e","status":"passed","time":{"start":1682142147888,"stop":1682142147889,"duration":1}},{"uid":"f58dc9c9bbc83f22","reportUrl":"https://module-federation.github.io/module-federation-examples/800//#testresult/f58dc9c9bbc83f22","status":"passed","time":{"start":1682137251391,"stop":1682137251392,"duration":1}},{"uid":"9dbe27313ba2347e","reportUrl":"https://module-federation.github.io/module-federation-examples/798//#testresult/9dbe27313ba2347e","status":"passed","time":{"start":1682130301826,"stop":1682130301827,"duration":1}},{"uid":"e44f05f043ddbd52","reportUrl":"https://module-federation.github.io/module-federation-examples/793//#testresult/e44f05f043ddbd52","status":"passed","time":{"start":1682071337705,"stop":1682071337705,"duration":0}}]},"tags":[]},"source":"5e8164e753372803.json","parameterValues":[]}