{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"Timed out retrying after 10000ms: Expected to find element: `h1`, but never found it.","children":[{"name":"Check App1 and App2 elements","uid":"ac25e3e17a8d581e","parentUid":"23fd062f6b4cc0af7a7ed54a88a82e22","status":"failed","time":{"start":1698545100912,"stop":1698545111361,"duration":10449},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"23fd062f6b4cc0af7a7ed54a88a82e22"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Cannot find module './src/components/Button.js'\nwhile loading \"./Button\" from webpack/container/reference/app2\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check App 1 built and running","uid":"2901e0ac6b17b09e","parentUid":"648b2475f8edd6983e414deda19cdcb4","status":"failed","time":{"start":1698545114039,"stop":1698545114040,"duration":1},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"Check buttons in App 1 exist","uid":"184c724d8f2091ce","parentUid":"648b2475f8edd6983e414deda19cdcb4","status":"failed","time":{"start":1698545114040,"stop":1698545114041,"duration":1},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"648b2475f8edd6983e414deda19cdcb4"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}