{"uid":"32d989736784afb8","name":"Checks that button in App 1 is not disabled","fullName":"Checks that button in App 1 is not disabled","historyId":"96aa8c65ac150f170b0d1f78b63386fc","time":{"start":1681976250273,"stop":1681976250906,"duration":633},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress.\n\n  > Loading script failed.\n(error: http://localhost:3002/remoteEntry.js)\nwhile loading \"./Button\" from 395\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress.\n\n  > Loading script failed.\n(error: http://localhost:3002/remoteEntry.js)\nwhile loading \"./Button\" from 395\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at 395 (http://localhost:3001/main.js:1:127)\n    at f (http://localhost:3001/main.js:1:604)\n    at <unknown> (http://localhost:3001/main.js:1:3714)\n    at f.I (http://localhost:3001/main.js:1:3874)\n    at <unknown> (http://localhost:3001/main.js:1:6157)\n    at 558 (http://localhost:3001/main.js:1:6291)\n    at <unknown> (http://localhost:3001/main.js:1:6676)\n    at Array.forEach (<anonymous>)\n    at f.f.consumes (http://localhost:3001/main.js:1:6506)\n    at <unknown> (http://localhost:3001/main.js:1:1322)","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress.\n\n  > Loading script failed.\n(error: http://localhost:3002/remoteEntry.js)\nwhile loading \"./Button\" from 395\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress.\n\n  > Loading script failed.\n(error: http://localhost:3002/remoteEntry.js)\nwhile loading \"./Button\" from 395\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at 395 (http://localhost:3001/main.js:1:127)\n    at f (http://localhost:3001/main.js:1:604)\n    at <unknown> (http://localhost:3001/main.js:1:3714)\n    at f.I (http://localhost:3001/main.js:1:3874)\n    at <unknown> (http://localhost:3001/main.js:1:6157)\n    at 558 (http://localhost:3001/main.js:1:6291)\n    at <unknown> (http://localhost:3001/main.js:1:6676)\n    at Array.forEach (<anonymous>)\n    at f.f.consumes (http://localhost:3001/main.js:1:6506)\n    at <unknown> (http://localhost:3001/main.js:1:1322)","steps":[{"name":"visit http://localhost:3001","time":{"start":1681976250373,"stop":1681976250901,"duration":528},"status":"failed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"uncaught exception ScriptExternalLoadError: Loading script failed.\n(error: http://localhost:3002/remoteEntry.js)\nwhile loading \"./Button\" from 395","time":{"start":1681976250901,"stop":1681976250901,"duration":0},"status":"failed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[{"uid":"fc2aaf79bbca456c","name":"e2e/commonChecks.cy.ts:2023-04-20T07:37:30.533Z:attempt-1","source":"fc2aaf79bbca456c.png","type":"image/png","size":157178},{"uid":"ef66cb20eeb14678","name":"video recording","source":"ef66cb20eeb14678.mp4","type":"video/mp4","size":3022553}],"parameters":[],"stepsCount":2,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"e2e.commonChecks.cy.ts"},{"name":"parentSuite","value":"Startup Code"},{"name":"suite","value":"It checks startup-code apps"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"1c7afac7d3890e58","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress.\n\n  > Loading script failed.\n(error: http://localhost:3002/remoteEntry.js)\nwhile loading \"./Button\" from 395\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1681976249632,"stop":1681976250267,"duration":635}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":2},"items":[{"uid":"4d5c232da26c92c9","reportUrl":"https://module-federation.github.io/module-federation-examples/773//#testresult/4d5c232da26c92c9","status":"passed","time":{"start":1681961987056,"stop":1681961987056,"duration":0}}]},"tags":[]},"source":"32d989736784afb8.json","parameterValues":[]}