{"uid":"a89512f6644d19ea","name":"Checks base page message & clicks each link by text & checks changes in page message and url & check reload does not revert changes","fullName":"Checks base page message & clicks each link by text & checks changes in page message and url & check reload does not revert changes","historyId":"6c15dae2fcf3123bf60328e73c6e830e","time":{"start":1682786455123,"stop":1682786455124,"duration":1},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at eval (webpack://react-nested-routers_shell/./src/routing/Router.tsx?:13:90)\n    at ./src/routing/Router.tsx (http://localhost:8080/src_bootstrap_tsx.js:48:1)\n    at __webpack_require__ (http://localhost:8080/main.js:377:33)\n    at fn (http://localhost:8080/main.js:717:21)\n    at eval (webpack://react-nested-routers_shell/./src/App.tsx?:8:73)\n    at ./src/App.tsx (http://localhost:8080/src_bootstrap_tsx.js:18:1)\n    at __webpack_require__ (http://localhost:8080/main.js:377:33)\n    at fn (http://localhost:8080/main.js:717:21)\n    at eval (webpack://react-nested-routers_shell/./src/bootstrap.tsx?:5:62)\n    at ./src/bootstrap.tsx (http://localhost:8080/src_bootstrap_tsx.js:28:1)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at eval (webpack://react-nested-routers_shell/./src/routing/Router.tsx?:13:90)\n    at ./src/routing/Router.tsx (http://localhost:8080/src_bootstrap_tsx.js:48:1)\n    at __webpack_require__ (http://localhost:8080/main.js:377:33)\n    at fn (http://localhost:8080/main.js:717:21)\n    at eval (webpack://react-nested-routers_shell/./src/App.tsx?:8:73)\n    at ./src/App.tsx (http://localhost:8080/src_bootstrap_tsx.js:18:1)\n    at __webpack_require__ (http://localhost:8080/main.js:377:33)\n    at fn (http://localhost:8080/main.js:717:21)\n    at eval (webpack://react-nested-routers_shell/./src/bootstrap.tsx?:5:62)\n    at ./src/bootstrap.tsx (http://localhost:8080/src_bootstrap_tsx.js:28:1)","steps":[],"attachments":[{"uid":"98ac4562a105a1b7","name":"e2e/runAll.cy.ts:2023-04-29T16:40:45.630Z","source":"98ac4562a105a1b7.png","type":"image/png","size":155388},{"uid":"340adb42bf803188","name":"video recording","source":"340adb42bf803188.mp4","type":"video/mp4","size":2557735}],"parameters":[],"stepsCount":0,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"e2e.runAll.cy.ts"},{"name":"parentSuite","value":"React Nested Routers"},{"name":"suite","value":"It checks shell app"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"63de7cba470cb59c","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682786449069,"stop":1682786449069,"duration":0}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":0,"skipped":0,"passed":15,"unknown":0,"total":17},"items":[{"uid":"82bcddec28675861","reportUrl":"https://module-federation.github.io/module-federation-examples/934//#testresult/82bcddec28675861","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682786455123,"stop":1682786455124,"duration":1}},{"uid":"28d3b9a8b70ee35c","reportUrl":"https://module-federation.github.io/module-federation-examples/873//#testresult/28d3b9a8b70ee35c","status":"passed","time":{"start":1682318654095,"stop":1682318654095,"duration":0}},{"uid":"6a7cfd76bc4a1222","reportUrl":"https://module-federation.github.io/module-federation-examples/857//#testresult/6a7cfd76bc4a1222","status":"passed","time":{"start":1682292527984,"stop":1682292527984,"duration":0}},{"uid":"be0fc25d86a64af3","reportUrl":"https://module-federation.github.io/module-federation-examples/847//#testresult/be0fc25d86a64af3","status":"passed","time":{"start":1682242554193,"stop":1682242554195,"duration":2}},{"uid":"5ee2cba73f91d01","reportUrl":"https://module-federation.github.io/module-federation-examples/842//#testresult/5ee2cba73f91d01","status":"passed","time":{"start":1682242554193,"stop":1682242554195,"duration":2}},{"uid":"96ea629ef6a7a10c","reportUrl":"https://module-federation.github.io/module-federation-examples/840//#testresult/96ea629ef6a7a10c","status":"passed","time":{"start":1682242554193,"stop":1682242554195,"duration":2}},{"uid":"f836ac509e2f5096","reportUrl":"https://module-federation.github.io/module-federation-examples/837//#testresult/f836ac509e2f5096","status":"passed","time":{"start":1682217345494,"stop":1682217345495,"duration":1}},{"uid":"cd7ac72daba4ad41","reportUrl":"https://module-federation.github.io/module-federation-examples/833//#testresult/cd7ac72daba4ad41","status":"passed","time":{"start":1682211463745,"stop":1682211463745,"duration":0}},{"uid":"7d99197a74d93b25","reportUrl":"https://module-federation.github.io/module-federation-examples/823//#testresult/7d99197a74d93b25","status":"passed","time":{"start":1682201545703,"stop":1682201545703,"duration":0}},{"uid":"1188e808d20670c7","reportUrl":"https://module-federation.github.io/module-federation-examples/820//#testresult/1188e808d20670c7","status":"passed","time":{"start":1682198362859,"stop":1682198362859,"duration":0}},{"uid":"d9e9758973aaab8a","reportUrl":"https://module-federation.github.io/module-federation-examples/819//#testresult/d9e9758973aaab8a","status":"passed","time":{"start":1682200067091,"stop":1682200067092,"duration":1}},{"uid":"9368dde9890ea6a2","reportUrl":"https://module-federation.github.io/module-federation-examples/806//#testresult/9368dde9890ea6a2","status":"passed","time":{"start":1682130301827,"stop":1682130301827,"duration":0}},{"uid":"dbb8931cb0e18744","reportUrl":"https://module-federation.github.io/module-federation-examples/804//#testresult/dbb8931cb0e18744","status":"passed","time":{"start":1682142147889,"stop":1682142147889,"duration":0}},{"uid":"6f160827a77dfd29","reportUrl":"https://module-federation.github.io/module-federation-examples/800//#testresult/6f160827a77dfd29","status":"passed","time":{"start":1682137251392,"stop":1682137251392,"duration":0}},{"uid":"c019d11b32c34014","reportUrl":"https://module-federation.github.io/module-federation-examples/798//#testresult/c019d11b32c34014","status":"passed","time":{"start":1682130301827,"stop":1682130301827,"duration":0}},{"uid":"ae56fd76c08ec6cb","reportUrl":"https://module-federation.github.io/module-federation-examples/793//#testresult/ae56fd76c08ec6cb","status":"passed","time":{"start":1682071337705,"stop":1682071337706,"duration":1}}]},"tags":[]},"source":"a89512f6644d19ea.json","parameterValues":[]}