{"uid":"7c80e780824fe51a","name":"Check button text visibility","fullName":"Check button text visibility","historyId":"7c80144d9b8c1d3ccd81c94fba6a1dcb","time":{"start":1698696858466,"stop":1698696858466,"duration":0},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Failed to fetch dynamically imported module: https://esm.sh/lodash.merge@4.6.2\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Failed to fetch dynamically imported module: https://esm.sh/lodash.merge@4.6.2\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Failed to fetch dynamically imported module: https://esm.sh/lodash.merge@4.6.2\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Failed to fetch dynamically imported module: https://esm.sh/lodash.merge@4.6.2\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","steps":[],"attachments":[{"uid":"f36c896f8811a2de","name":"e2e/checkApplications.cy.ts:2023-10-30T20:14:10.654Z","source":"f36c896f8811a2de.png","type":"image/png","size":145425},{"uid":"4e2a8c44a84d489d","name":"video recording","source":"4e2a8c44a84d489d.mp4","type":"video/mp4","size":2085945}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"e2e.checkApplications.cy.ts"},{"name":"parentSuite","value":"Federated npm"},{"name":"suite","value":"Check App 1"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"7c80e780824fe51a.json","parameterValues":[]}