{"uid":"c3dbd6fb63ad7d66","name":"Checks page message visibility","fullName":"Checks page message visibility","historyId":"15aa3e52e6044dce7b577028335a53fd","time":{"start":1682973291033,"stop":1682973291830,"duration":797},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at createRouter (webpack://react-nested-routers_app2/./src/routing/router-factory.ts?:14:81)\n    at mount (webpack://react-nested-routers_app2/./src/bootstrap.tsx?:21:85)\n    at eval (webpack://react-nested-routers_app2/./src/index.ts?:5:3)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at createRouter (webpack://react-nested-routers_app2/./src/routing/router-factory.ts?:14:81)\n    at mount (webpack://react-nested-routers_app2/./src/bootstrap.tsx?:21:85)\n    at eval (webpack://react-nested-routers_app2/./src/index.ts?:5:3)","steps":[{"name":"visit http://localhost:8082","time":{"start":1682973291151,"stop":1682973291365,"duration":214},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"get div","time":{"start":1682973291365,"stop":1682973291376,"duration":11},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"contains Page A from App2","time":{"start":1682973291376,"stop":1682973291828,"duration":452},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"assert expected **:cy-contains('Page A from App2'), [type='submit'][value~='Page A from App2']** to be **visible**","time":{"start":1682973291827,"stop":1682973291827,"duration":0},"status":"failed","steps":[],"attachments":[],"parameters":[{"name":"actual","value":":cy-contains('Page A from App2'), [type='submit'][value~='Page A from App2']"},{"name":"expected","value":"visible"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"uncaught exception TypeError: (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function","time":{"start":1682973291828,"stop":1682973291828,"duration":0},"status":"failed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[{"uid":"b4a1ef5b64ea0b86","name":"e2e/runAll.cy.ts:2023-05-01T20:34:51.430Z:attempt-1","source":"b4a1ef5b64ea0b86.png","type":"image/png","size":153873},{"uid":"7cb66c56f0245b4c","name":"video recording","source":"7cb66c56f0245b4c.mp4","type":"video/mp4","size":2570997}],"parameters":[],"stepsCount":5,"attachmentsCount":2,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"package","value":"e2e.runAll.cy.ts"},{"name":"parentSuite","value":"React Nested Routers"},{"name":"suite","value":"It checks app1/app2"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"90c2790fe3cfafee","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682973289955,"stop":1682973291020,"duration":1065}},{"uid":"2bcd7c3d08cf7819","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682973281869,"stop":1682973283069,"duration":1200}},{"uid":"600aa9742a7ab347","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682970715318,"stop":1682970716073,"duration":755}},{"uid":"bfa4bc1281b47785","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682970714213,"stop":1682970715306,"duration":1093}},{"uid":"128d8abe3932bb9b","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682970707276,"stop":1682970708259,"duration":983}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":6,"broken":0,"skipped":0,"passed":15,"unknown":0,"total":21},"items":[{"uid":"c2778919bcbd2a1a","reportUrl":"https://module-federation.github.io/module-federation-examples/942//#testresult/c2778919bcbd2a1a","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682970715318,"stop":1682970716073,"duration":755}},{"uid":"ee53dcd5a24c26e6","reportUrl":"https://module-federation.github.io/module-federation-examples/941//#testresult/ee53dcd5a24c26e6","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682966994397,"stop":1682966995392,"duration":995}},{"uid":"f6e4e57ef1aa9334","reportUrl":"https://module-federation.github.io/module-federation-examples/940//#testresult/f6e4e57ef1aa9334","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682964269916,"stop":1682964270736,"duration":820}},{"uid":"ca2d3d729e6e30ca","reportUrl":"https://module-federation.github.io/module-federation-examples/937//#testresult/ca2d3d729e6e30ca","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682786456104,"stop":1682786456792,"duration":688}},{"uid":"58d355523b8c4faa","reportUrl":"https://module-federation.github.io/module-federation-examples/934//#testresult/58d355523b8c4faa","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1682786456104,"stop":1682786456792,"duration":688}},{"uid":"448710af9ef9494a","reportUrl":"https://module-federation.github.io/module-federation-examples/873//#testresult/448710af9ef9494a","status":"passed","time":{"start":1682318654097,"stop":1682318655034,"duration":937}},{"uid":"2c32161a74e55a32","reportUrl":"https://module-federation.github.io/module-federation-examples/857//#testresult/2c32161a74e55a32","status":"passed","time":{"start":1682292527985,"stop":1682292528633,"duration":648}},{"uid":"25ccd553e5690ce0","reportUrl":"https://module-federation.github.io/module-federation-examples/847//#testresult/25ccd553e5690ce0","status":"passed","time":{"start":1682242554197,"stop":1682242554972,"duration":775}},{"uid":"8c245b7d460a449e","reportUrl":"https://module-federation.github.io/module-federation-examples/842//#testresult/8c245b7d460a449e","status":"passed","time":{"start":1682242554197,"stop":1682242554972,"duration":775}},{"uid":"755313c7b713e083","reportUrl":"https://module-federation.github.io/module-federation-examples/840//#testresult/755313c7b713e083","status":"passed","time":{"start":1682242554197,"stop":1682242554972,"duration":775}},{"uid":"b324e3644d3a27cd","reportUrl":"https://module-federation.github.io/module-federation-examples/837//#testresult/b324e3644d3a27cd","status":"passed","time":{"start":1682217345496,"stop":1682217346703,"duration":1207}},{"uid":"52cf48dc49a110de","reportUrl":"https://module-federation.github.io/module-federation-examples/833//#testresult/52cf48dc49a110de","status":"passed","time":{"start":1682211463747,"stop":1682211464436,"duration":689}},{"uid":"eefd3b41eb5973a","reportUrl":"https://module-federation.github.io/module-federation-examples/823//#testresult/eefd3b41eb5973a","status":"passed","time":{"start":1682201545705,"stop":1682201546341,"duration":636}},{"uid":"cfb96de0e03ef4fd","reportUrl":"https://module-federation.github.io/module-federation-examples/820//#testresult/cfb96de0e03ef4fd","status":"passed","time":{"start":1682198362861,"stop":1682198363610,"duration":749}},{"uid":"e785be5d4ed774c5","reportUrl":"https://module-federation.github.io/module-federation-examples/819//#testresult/e785be5d4ed774c5","status":"passed","time":{"start":1682200067093,"stop":1682200068115,"duration":1022}},{"uid":"8a1d42852eebf13e","reportUrl":"https://module-federation.github.io/module-federation-examples/806//#testresult/8a1d42852eebf13e","status":"passed","time":{"start":1682130301828,"stop":1682130302505,"duration":677}},{"uid":"d6d89100df07b6fe","reportUrl":"https://module-federation.github.io/module-federation-examples/804//#testresult/d6d89100df07b6fe","status":"passed","time":{"start":1682142147890,"stop":1682142148738,"duration":848}},{"uid":"f509e559e4051768","reportUrl":"https://module-federation.github.io/module-federation-examples/800//#testresult/f509e559e4051768","status":"passed","time":{"start":1682137251396,"stop":1682137252107,"duration":711}},{"uid":"34befc094fb4be4c","reportUrl":"https://module-federation.github.io/module-federation-examples/798//#testresult/34befc094fb4be4c","status":"passed","time":{"start":1682130301828,"stop":1682130302505,"duration":677}},{"uid":"67afc6ccb9b954e9","reportUrl":"https://module-federation.github.io/module-federation-examples/793//#testresult/67afc6ccb9b954e9","status":"passed","time":{"start":1682071337707,"stop":1682071338602,"duration":895}}]},"tags":[]},"source":"c3dbd6fb63ad7d66.json","parameterValues":[]}