{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"Timed out retrying after 10000ms: Expected to find element: `h1`, but never found it.","children":[{"name":"Check App1 and App2 elements","uid":"12caebb565c380e1","parentUid":"23fd062f6b4cc0af7a7ed54a88a82e22","status":"failed","time":{"start":1698528371373,"stop":1698528382042,"duration":10669},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"23fd062f6b4cc0af7a7ed54a88a82e22"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Loading script failed.\n(error: http://localhost:3002/remoteEntry.js)\nwhile loading \"./Dialog\" from webpack/container/reference/app_02\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check Main Tab Functionality","uid":"735c851027f31e37","parentUid":"19531b667667aff265858600cd024375","status":"failed","time":{"start":1698528968518,"stop":1698528970106,"duration":1588},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":5,"retriesStatusChange":true,"parameters":[],"tags":[]},{"name":"Check Dialog elements","uid":"ddf93c34b49ebcdc","parentUid":"19531b667667aff265858600cd024375","status":"failed","time":{"start":1698528971372,"stop":1698528972262,"duration":890},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":5,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"19531b667667aff265858600cd024375"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Loading script failed.\n(error: http://localhost:3002/remoteEntry.js)\nwhile loading \"./Tabs\" from webpack/container/reference/app_02\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check Routing elements","uid":"40235f4b636a793a","parentUid":"03e4ef5701b94c5b072672d1a9cc5192","status":"failed","time":{"start":1698528973919,"stop":1698528975072,"duration":1153},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":5,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"03e4ef5701b94c5b072672d1a9cc5192"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Additional keys were returned from `getServerSideProps`. Properties intended for your component must be nested under the `props` key, e.g.:\n\n\treturn { props: { title: 'My Title', content: '...' } }\n\nKeys that need to be moved: userId, id, title, completed.\nRead more: https://nextjs.org/docs/messages/invalid-getserversideprops-value\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check that Shop navigation link works","uid":"bf3c02c44906cf7","parentUid":"9923ecdd3da820d4b0811512ad94f2f1","status":"failed","time":{"start":1698531084274,"stop":1698531088978,"duration":4704},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"Check that Shop text navigation link works","uid":"3966fb80e63ce451","parentUid":"9923ecdd3da820d4b0811512ad94f2f1","status":"failed","time":{"start":1698531121734,"stop":1698531126113,"duration":4379},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":3,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"9923ecdd3da820d4b0811512ad94f2f1"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"`cy.visit()` failed trying to load:\n\nhttp://localhost:3002/\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: connect ECONNREFUSED 127.0.0.1:3002\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer","children":[{"name":"Check App build and running & Check app elements exist","uid":"3a380fcd803f4dbb","parentUid":"2683fe2a96f02bf2df6b4ced1b19732c","status":"broken","time":{"start":1698528976054,"stop":1698528976974,"duration":920},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":13,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"2683fe2a96f02bf2df6b4ced1b19732c"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Cannot find module 'app1/Button'\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check elements exist","uid":"f2f0931c686972de","parentUid":"d2140daa7579ccd0f3e01294a2cdf6c2","status":"broken","time":{"start":1698530793490,"stop":1698530794071,"duration":581},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"d2140daa7579ccd0f3e01294a2cdf6c2"},{"name":"`cy.visit()` failed trying to load:\n\nhttp://localhost:3002//shop\n\nThe response we received from your web server was:\n\n  > 500: Internal Server Error\n\nThis was considered a failure because the status code was not `2xx`.\n\nThis http request was redirected '1' time to:\n\n  - 308: http://localhost:3002/shop\n\nIf you do not want status codes to cause failures pass the option: `failOnStatusCode: false`","children":[{"name":"Check the header content of Shop page","uid":"de6cbfeb93e49735","parentUid":"fc7d2bf7fe16529721b0bcd46f598781","status":"broken","time":{"start":1698531095366,"stop":1698531095956,"duration":590},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":[]}],"uid":"fc7d2bf7fe16529721b0bcd46f598781"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}